services:
  - type: web
    name: rbf-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn rbf_project.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: rbf_project.settings
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
